# Используем официальный Node.js образ
FROM node:20

# Рабочая директория в контейнере
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной исходный код
COPY . .

# Next.js dev-сервер работает на порту 3000
EXPOSE 3000

# Запускаем в режиме разработки
CMD ["npm", "run", "dev"]   
