version: '3.8'

services:
  app:
    build: ./laravel_app/
    container_name: split_receipt_backend
    env_file: .env
    volumes:
      - static:/static

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: ivanmareev/split_receipt_frontend:latest
    container_name: react_frontend
    networks:
      - app-network
    expose:
      - 80
    depends_on:
      - app
    restart: unless-stopped

  gateway:
    build: ./gateway/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media

volumes:
  pg_data:
  static:
  media:
