services:
  app:
    build: ./laravel_app/
    container_name: laravel_app
    env_file: .env
    ports:
      - "9000:9000"

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  react_frontend:
    image: ivanmareev/split_receipt_frontend:latest
    container_name: react_frontend
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - frontend_build:/app/build

  gateway:
    build: ./gateway/
    container_name: gateway_nginx
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - app
      - react_frontend
    networks:
      - app-network

volumes:
  pgdata:
  frontend_build:

networks:
  app-network:
    driver: bridge
