networks:
  app-network:
    driver: bridge

services:
  app:
    image: ivanmareev/split_receipt_backend:latest
    container_name: laravel_app
    expose:
      - 9000
    env_file:
      - ./split_receipt_backend/.env
    depends_on:
      - db
    networks:
      - app-network  
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: ivanmareev/split_receipt_frontend:latest
    container_name: react_frontend
    networks:
      - app-network
    expose:
      - 80
    depends_on:
      - app
    restart: unless-stopped

  gateway:
    image: ivanmareev/split_receipt_gateway:latest 
    container_name: gateway_nginx
    ports:
      - 80:80
    depends_on:
      - app
      - frontend
    networks:
      - app-network  
    restart: unless-stopped

volumes:
  pgdata:

