version: '3.8'

services:
  app:
    build:
      context: ./split_receipt_backend
    container_name: laravel_app_dev
    volumes:
      - ./split_receipt_backend:/var/www
    ports:
      - 9000:9000
    env_file:
      - ./split_receipt_backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./split_receipt_frontend
      dockerfile: Dockerfile.dev
    container_name: react_frontend_dev
    volumes:
      - ./split_receipt_frontend:/app
    command: npm run dev
    ports:
      - 5173:5173 # или 3000, если CRA
    depends_on:
      - app
  gateway:
    entrypoint: ["echo", "skipping gateway in dev mode"]   

  db:
    image: postgres:15
    container_name: laravel_db_dev
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
