volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
  backend:
    build: ./backend/
    container_name: backend
    env_file: .env
    volumes:
      - static:/static
  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - "3000:80"
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
