version: '3.8'

services:
  app:
    image: ivanmareev/split_receipt_backend:latest
    container_name: laravel_app
    expose:
      - 9000
    env_file:
      - ./split_receipt_backend/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: root/split_receipt_frontend:latest
    container_name: react_frontend
    expose:
      - 80
    depends_on:
      - app
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
    container_name: gateway_nginx
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - frontend
    restart: unless-stopped

volumes:
  pgdata:
