version: '3.8'

services:
  app:
    build: ./laravel_app/
    container_name: laravel_app
    env_file: .env
    ports:
      - "9000:9000"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  react_frontend:
    build:
      context: ./frontend  # путь к React-проекту
    container_name: react_frontend
    volumes:
      - frontend_static:/app/dist
    networks:
      - app-network

  gateway:
    build: ./gateway/
    container_name: gateway_nginx
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - app
      - react_frontend
    volumes:
      - ./gateway/default.conf.template:/etc/nginx/templates/default.conf.template
      - frontend_static:/static:ro
    networks:
      - app-network

volumes:
  pgdata:
  frontend_static:

networks:
  app-network:
    driver: bridge
