volumes:
  pgdata:
  static:
  media:

services:
  react_frontend:
    build: ./react_frontend/
    container_name: frontend
    networks:
      - app-network
    volumes:
      - static:/usr/share/nginx/html  # Монтируем volume static внутрь react_frontend в папку, куда собирается статика
    command: sh -c "npm install && npm run build && cp -r dist/* /usr/share/nginx/html"  # Собираем и копируем в volume

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    networks:
      - app-network
    volumes:
      - static:/usr/share/nginx/html  # Монтируем тот же volume static в nginx, чтобы отдавать статику

networks:
  app-network:
