
volumes:
  pgdata:
  static:
  media:

services:
  app:
    build: ./laravel_app/
    container_name: laravel_app
    env_file: .env
    ports:
      - "9000:9000"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  react_frontend:
    env_file: .env
    build: ./react_frontend/
    container_name: frontend
    command: cp -r /app/dist/. /static/
    volumes:
      - static:/static
    networks:
      - app-network

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    networks:
      - app-network

networks:
  app-network:
