volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
  backend:
    build: ./backend/
    container_name: backend
    env_file: .env
    volumes:
      - static:/static
  frontend:
    image: ivanmareev/split_receipt_frontend:latest
    container_name: frontend
    env_file: .env
    command: sh -c "cp -r /app/build/. /static"
    volumes:
      - static:/static
    ports:
      - "3000:3000"
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
